name: Pull Request
about: Create a PR to contribute changes to ClassBuddy
title: "feat: <short summary>"
labels: ["needs-review"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your contribution! Please provide the details below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly explain the changes and the motivation.
    validations:
      required: true

  - type: checkboxes
    id: type
    attributes:
      label: Type of change
      options:
        - label: Feature
        - label: Bug fix
        - label: Documentation update
        - label: Refactor/Chore
        - label: Tests

  - type: textarea
    id: testing
    attributes:
      label: Test Plan
      description: How did you test these changes?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I ran the backend tests (pytest) and they pass
        - label: I ran the mobile tests (npm test) and they pass
        - label: I updated documentation where needed
        - label: I followed the coding style guidelines
        - label: I ran linters/formatters (Black/ESLint)
