# Railway Deployment Configuration
# Deploy to Railway: https://railway.app

[build]
cmd = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"

[variables]
SECRET_KEY = "lAHyy8wVWCFYCbkRdk_39PLMBm14p2n6X-rut7CsMzw"
DOCS_ENABLED = "true"
ENVIRONMENT = "production"
LOG_LEVEL = "INFO"
PORT = "8000"
