blank_issues_enabled: false
contact_links:
  - name: Security issues
    url: mailto:shivjani2005@gmail.com
    about: Please email us about security vulnerabilities instead of opening a public issue.
