name: Question
description: Ask a question about ClassBuddy
title: "[QUESTION] "
labels: ["question", "help wanted"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! 🤔 We're here to help.
        
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please be as detailed as possible
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      options:
        - Setup/Installation
        - Usage/How-to
        - Development
        - Deployment
        - Mobile Development
        - API Usage
        - Contributing
        - General

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: What have you tried so far? Any relevant code snippets or configurations?

  - type: checkboxes
    id: searched
    attributes:
      label: Research Done
      description: Have you checked these resources first?
      options:
        - label: I've read the README.md
        - label: I've checked existing issues
        - label: I've looked at the documentation
        - label: I've searched online for solutions

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Jani-shiv/clasbuddy/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
